export const FETCH_ALL_CATEGORY = 'FETCH_ALL_CATEGORY';
export const FETCH_ALL_ALPHABETS = 'FETCH_ALL_ALPHABETS';
export const FETCH_ALL_SUB_CATEGORY = 'FETCH_ALL_SUB_CATEGORY';
export const FETCH_ALL_ALPHABETS_SUCCESS = 'FETCH_ALL_ALPHABETS_SUCCESS';
export const FETCH_ALL_SUBCATEGORY_SUCCESS = 'FETCH_ALL_SUBCATEGORY_SUCCESS';
export const FETCH_ALL_CATEGORY_SUCCESS = 'FETCH_ALL_CATEGORY_SUCCESS';
export const SET_LOADER_FALSE = 'SET_LOADER_FALSE';
export const SET_LOADER_TRUE = 'SET_LOADER_TRUE';